apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
      - name: service-c
        image: harbor.eencloud.com/qa/service-a
        # this is necessary or else it will pull from the docker repository rather than local
        #imagePullPolicy: Never
        ports:
        - containerPort: 5000
